ELK-EKS- Monitoring :

What is EFK Stak:
  The EFK stack is a collection of open-source tools that are commonly used for log management and analysis.

Elasticsearch: This is a distributed search and analytics engine that is used to store and index data.

Fluentd: This is a data collector that is used to aggregate logs from various sources, such as applications, servers, and network devices.

Kibana: This is a web-based user interface that is used to visualize and analyze data stored in Elasticsearch.

Together, the EFK stack provides a powerful and flexible solution for collecting, storing, and analyzing log data from multiple sources.

It is often used in modern cloud-based environments, such as Kubernetes, to provide centralized logging and monitoring capabilities for applications and services.

Spring boot application logs monitoring using EFK stack in Kubernetes cluster

ELK Setup:
Types of Monitoring
- White Box Monitoring  == In & Out Monitoring
- Black Box Monitoring  == OutSide Monitoring

Incident Management Team:
Priority & Severity & Service Level Agreement

# Rules to Check the Monitoring
Latency:
1: Time Taking the service to respond

Traffic:
1: How many users can access with in specified time to our system

Errors:
1: Server Side Errors -- 500
2: Client Side Errors -- 400
3: Redirection Errors -- 300
4: Success Messages -- 200

Saturation:
1: Threshold value where we should get messages

Elastic LogStash Kibana (ELK)
1: Originally it was developed for Searching Mechanism

*Elastic search is a Database where we store everything
*Kibana is a UI It connects to Elastic Search To show the data
*LogStash is used for Filter the data coming from agents
*FileBeat will access the log file and Push those to Elastic Search database






